name: sendbird_chat_sdk
description: With Sendbird Chat for Flutter, you can easily build an in-app chat with all the essential messaging features.
version: 4.0.13
homepage: https://sendbird.com
repository: https://github.com/sendbird/sendbird-chat-sdk-flutter
documentation: https://sendbird.com/docs/chat/sdk/v4/flutter/getting-started/send-first-message

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  uuid: ^3.0.7
  json_annotation: ^4.8.1
  encrypt: ^5.0.1
  shared_preferences: ^2.1.2
  http: ^0.13.6
  logger: ^1.4.0
  mime: ^1.0.4
  connectivity_plus: ^4.0.1
  http_parser: ^4.0.2
  web_socket_channel: ^2.4.0
  universal_io: ^2.2.0
  async: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.22.0
  stack_trace: ^1.11.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
