name: sendbird_sdk
description: The Flutter SDK for Sendbird Chat brings modern messenger chat features to your iOS and Android deployments.. 
version: 3.0.10
homepage: https://www.sendbird.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.13
  uuid: ^2.2.2
  json_annotation: ^3.1.0
  encrypt: ^4.1.0
  shared_preferences: ^0.5.12+2
  http: ^0.12.0
  device_info: ^1.0.0
  logger: ^0.9.4
  mime: ^0.9.7
  yaml: ^2.2.1
  connectivity: ^2.0.2
  meta: ^1.2.0
  http_parser: ^3.1.0

dev_dependencies:
  test: ^1.15.5
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  build_runner: ^1.0.0
  stack_trace: ^1.9.6
  pedantic: ^1.0.0